/* Image helpers -----------------------------------------------------
   Photographs are self-hosted in /public/images as WebP at three
   widths (480 / 960 / 1600), generated by scripts/build-images.py.
   A ref is the base filename, e.g. 'maara-after'.

   Any ref starting with "/" or "http" is passed straight through, so
   you can drop a single new photo in without regenerating anything. */

const WIDTHS = [480, 960, 1600]
const isPath = (r) => r.startsWith('/') || r.startsWith('http')

const pick = (w) => WIDTHS.find((c) => c >= w) ?? WIDTHS[WIDTHS.length - 1]

export function src(ref, w = 960) {
  if (!ref) return ''
  if (isPath(ref)) return ref
  return `/images/${ref}-${pick(w)}.webp`
}

export function srcSet(ref) {
  if (!ref || isPath(ref)) return undefined
  return WIDTHS.map((w) => `/images/${ref}-${w}.webp ${w}w`).join(', ')
}
