/* Image helpers -----------------------------------------------------
   Photographs are self-hosted in /public/images as WebP, generated by
   scripts/build-images.py. A ref is the base filename, e.g. 'hero-main'.

   Which widths exist varies per image: the build never upscales past a
   source's native size, so a small photo has fewer variants than a
   camera original. The generated manifest records what was actually
   written — naming a file in a srcset that was never generated makes
   the browser fetch a 404 and render nothing.

   Any ref starting with "/" or "http" is passed straight through. */

import manifest from './image-manifest.json'

const FALLBACK = [480, 960, 1600]
const isPath = (r) => r.startsWith('/') || r.startsWith('http')
const widthsFor = (ref) => manifest[ref] ?? FALLBACK

export function src(ref, w = 960) {
  if (!ref) return ''
  if (isPath(ref)) return ref
  const widths = widthsFor(ref)
  const pick = widths.find((c) => c >= w) ?? widths[widths.length - 1]
  return `/images/${ref}-${pick}.webp`
}

export function srcSet(ref) {
  if (!ref || isPath(ref)) return undefined
  return widthsFor(ref)
    .map((w) => `/images/${ref}-${w}.webp ${w}w`)
    .join(', ')
}
